### ISSUE TITLE
cannot build with [ionic cordova build android --prod]

### ISSUE THREAD

**Issue by Smando87** [zyra/ionic-image-loader#129]
Running 
`ionic cordova build android --prod`

fail with

```
[14:54:00]  ngc started ... 
[14:54:06]  typescript error 
            ("ton ion-item *ngFor="let item of items" (click)="itemSelected(item)"> <ion-card href> [ERROR 
            ->]<img-loader useImg src="https://cdn.pixabay.com/photo/2017/01/06/19/15/soap-bubble-1958650_960_720.jp") 

Error: The Angular AoT build failed. See the issues above
    at /home/test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:38
    at step (/home/testnode_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/home/test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/home/test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
[14:54:06]  copy finished in 5.99 s 
```

ionic info:
```[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.5.1 
    OS                : Linux 4.14

Environment Variables:


Misc:

    backend : legacy

```
package.json
```{
  "name": "aaaaaaaaaaa",
  "version": "0.0.0",
  "description": "aaaaaaaaaaaaa",
  "license": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "build": "ionic-app-scripts build",
    "clean": "ionic-app-scripts clean",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "npm run build",
    "ionic:serve": "npm run serve",
    "ionic:lint": "npm run lint"
  },
  "dependencies": {
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@ionic-native/app-version": "^4.2.1",
    "@ionic-native/autostart": "^4.5.2",
    "@ionic-native/background-mode": "^4.5.2",
    "@ionic-native/calendar": "^4.3.2",
    "@ionic-native/call-number": "^4.5.2",
    "@ionic-native/camera": "^4.3.2",
    "@ionic-native/core": "4.5.2",
    "@ionic-native/file": "^4.5.2",
    "@ionic-native/file-transfer": "^4.5.2",
    "@ionic-native/http": "^4.3.0",
    "@ionic-native/in-app-browser": "^3.13.1",
    "@ionic-native/launch-navigator": "^4.3.2",
    "@ionic-native/local-notifications": "^4.5.2",
    "@ionic-native/phonegap-local-notification": "^4.5.2",
    "@ionic-native/photo-viewer": "^4.5.2",
    "@ionic-native/push": "^4.5.2",
    "@ionic-native/splash-screen": "^4.3.1",
    "@ionic-native/status-bar": "^4.3.1",
    "@ionic/storage": "^2.1.3",
    "angular-imgcache.js": "^1.2.0",
    "call-number": "^1.0.1",
    "com-sarriaroman-photoviewer": "^1.1.11",
    "cordova-android": "~7.0.0",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-advanced-http": "^1.9.1",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-autostart": "^2.0.1",
    "cordova-plugin-background-mode": "^0.7.2",
    "cordova-plugin-badge": "^0.8.6",
    "cordova-plugin-calendar": "^4.6.0",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^1.1.6",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-file": "^5.0.0",
    "cordova-plugin-file-transfer": "^1.7.0",
    "cordova-plugin-inappbrowser": "^1.7.2",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.3",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-sqlite-storage": "^2.2.0",
    "ionic-angular": "3.9.2",
    "ionic-image-loader": "^5.0.0",
    "ionic-platform-web-client": "^0.7.1",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "me.tonny.cordova.plugins.multidex": "https://github.com/jwall149/cordova-multidex",
    "mx.ferreyra.callnumber": "0.0.2",
    "ng2-cookies": "^1.0.12",
    "phonegap-plugin-local-notification": "^1.0.1",
    "phonegap-plugin-push": "^2.1.2",
    "remove": "^0.1.5",
    "rxjs": "5.5.2",
    "servicestack-client": "0.0.39",
    "sw-toolbox": "3.6.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.1.2",
    "underscore": "^1.8.3",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.5",
    "ionic": "3.9.1",
    "typescript": "~2.4.2"
  },
  "config": {},
  "cordova": {
    "platforms": [
      "android"
    ],
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-calendar": {},
      "cordova-plugin-camera": {},
      "mx.ferreyra.callnumber": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-file-transfer": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-file": {},
      "cordova-plugin-advanced-http": {},
      "me.tonny.cordova.plugins.multidex": {},
      "uk.co.workingedge.phonegap.plugin.launchnavigator": {},
      "call-number": {},
      "phonegap-plugin-push": {
        "FCM_VERSION": "11.0.1"
      },
      "com-sarriaroman-photoviewer": {},
      "cordova-plugin-background-mode": {},
      "cordova-plugin-local-notification": {},
      "phonegap-plugin-local-notification": {},
      "cordova-plugin-autostart": {}
    }
  }
}```

**Comment by ihadeed** [comment]
Need the full error message/log.
