### ISSUE TITLE
[BUG] 4.2.0 breaks builds

### ISSUE THREAD

**Issue by CelsoSantos** [zyra/ionic-image-loader#95]
Hello,

The latest version seems to break the builds, at least with Ionic App Scripts v1.2.2.

Error output:
```
+ npm run build

> com.brandbassador@ build /var/lib/jenkins/workspace/STG-IonicApp
> node --max-old-space-size=2048 ./node_modules/.bin/ionic-app-scripts build

[14:52:39]  ionic-app-scripts 1.2.2 
[14:52:39]  build dev started ... 
[14:52:39]  clean started ... 
[14:52:39]  clean finished in 1 ms 
[14:52:39]  copy started ... 
[14:52:39]  transpile started ... 
[14:52:46]  typescript: node_modules/ionic-image-loader/dist/components/img-loader.d.ts, line: 1 
            Module '"/var/lib/jenkins/workspace/STG-IonicApp/node_modules/@angular/core/index"' has no exported member 
            'Renderer2'. 

       L1:  import { ElementRef, Renderer2, OnInit, EventEmitter } from '@angular/core';
       L2:  import { ImageLoader } from '../providers/image-loader';

[14:52:46]  ionic-app-script task: "build" 
[14:52:46]  Error: Failed to transpile program 
Error: Failed to transpile program
    at BuildError.Error (native)
    at new BuildError (/var/lib/jenkins/workspace/STG-IonicApp/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /var/lib/jenkins/workspace/STG-IonicApp/node_modules/@ionic/app-scripts/dist/transpile.js:102:20
    at transpileWorker (/var/lib/jenkins/workspace/STG-IonicApp/node_modules/@ionic/app-scripts/dist/transpile.js:68:12)
    at Object.transpile (/var/lib/jenkins/workspace/STG-IonicApp/node_modules/@ionic/app-scripts/dist/transpile.js:26:12)
    at buildProject (/var/lib/jenkins/workspace/STG-IonicApp/node_modules/@ionic/app-scripts/dist/build.js:98:78)
    at /var/lib/jenkins/workspace/STG-IonicApp/node_modules/@ionic/app-scripts/dist/build.js:46:16
```

Ionic Info:
```
[jenkins@bb-jenkins STG-IonicApp]$ ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.6.0
Xcode version: Not installed
```

**Comment by ihadeed** [comment]
I think `Renderer2` was introduced in Angular 4.x, and IIRC `ionic-angular@2.x` uses Angular 2.x

I'll replace `Renderer` with `Renderer` and publish a new release soon.
